### ISSUE TITLE
Integrate updated Input Iterables

### ISSUE THREAD

**Issue by rizo** [fold-lang/fold#11]
Try to implement input iterable instance for Lexer.

**Tasks**:

- [x] Update Iter library with better interfaces (already used in Pure)
- [x] Replace parser input module by input iterable
- [x] Implement Input Iterable instance for Lexer
- [x] Update Pratt state module
- [x] Ensure expression parsing terminates properly (with or without the EOF token)

**Comment by rizo** [comment]
A working implementation exists at the moment. The lever can be redefined to strictly act as an iterable in the future.
